DockerFiles/dockerInstructions.txt

The Issue was that this particular piece of instruction was only designed to work for Windows Users, and some of the variables in the listed commands were both vague and undefined. I Decided to include support for all operating systems, and some more context as to what it was we were doing with the steps in this instruction set.

Improve Docker Instructions for readability and OS inclusion

---

Frontend/src/pages/ExploreSystems.js

What Changed:
- added alert pop up if we cannot connect to database
- changed inaccurate "loading database" message to red error message
Why:
- It was difficult to tell if the data was still loading or if there was an issue. The web app did nothing to communicate this,
- The code displayed an misdirecting inaccurate loading message in place of an error message.

Adding_alert_for_database_issues

---

.gitignore

Issue: unnecessary env files getting added to PR
What changed? - Added venv and docker files to gitignore

updated gitignore to avoid Docker files and venv folders

---

Frontend/src/pages/ExploreSystems.js

Problem: no result stats being displayed
Action: need to display at least the number of results
Status: 
- Now displays the number of maps
- Partial implementation to store average height
Files changed: ExploreSystems.js

Display Number of Maps

---

Backend/PostgresConnector.py
Backend/server.py
Frontend/package.json
Frontend/src/api/routes.js

How we run the application does not change. Just resolved CORS erros.

Resolved CORS errors on mac

---

Backend/PostgresConnector.py
Backend/server.py
Frontend/src/api/routes.js
Frontend/src/pages/ExploreSystems.js

Goal: Implement 4 stats: Average Height, Number of Newtonian Systems, Average Resultant, and Number of PCF Systems
Files changed: ExploreSystems.js, Postrgress_Connector.py, Server.py, Routes.js
- Implemented Stats: Num PCF, Avg Height, Avg Resultant, Number of Newtonian, 
- Added funtion getStatisticas to Postgress Connector to calculate the statistics
- Added Function fetchStatistics ti ExploreSystems.js to use getStatistics
- Added getStatistics to routes and server.py to allow for the funtion to be used between frontend and backend over port 5000
- Added useState to ExploreSystems.js to store the statistics.
- Removed text field from stats box (not sure why it was there to begin with
Future Action: There are still more statistics to implement

Implementing 4 statistics #30

---

Backend/PostgresConnector.py
Backend/server.py
Frontend/src/api/routes.js
Frontend/src/pages/ExploreSystems.js

Revert "Implementing 4 statistics #30"

---

Backend/PostgresConnector.py
Backend/server.py
Frontend/src/api/routes.js
Frontend/src/pages/ExploreSystems.js

What changed: Implementing stats: nummaps, averageHeight, avgResultant, numPcf, numNewton
Files Changed: systems.py, routes.js, exploreSystems.js, postgres_connector.py
- added function getStatistics to postgres_connector
- added function fetchStatistics to access that function from esploreSystems
- edited systems.py and routes.js to allow access to getStatistics through the api
- created a useState in ExploreSystems to store stats
- edited html to display stats in exploreSystems
Why: not fully implemented stats
Future action: still more stats to implement

Implement stats #30

---

Frontend/src/errorreport/ReportGeneralError.js
Frontend/src/errorreport/ReportMajorError.js
Frontend/src/pages/ExploreSystems.js

The solution of fix error handling #33 mainly consists of the following two aspects:
There are two types of error module functions that need to be developed. One is for reporting major errors. Another is for reporting a toast error kind of thing for warnings and minor errors. To save the error reporting functions for global calling and reuse, a folder named "**errorreport**" is created first in the path "**dads/Frontend/src/**".
- **Major Error Module Function:** Developed and added the file **ReportMajorError.js** to the path "**dads/Frontend/src/errorreport**". In this file, a function named "**ReportMajorError**" is designed. Any major error can be reported by calling this function globally to pop up the error message.
- **General Error Module Function:** A file named …

Fix error handling #33

---

Backend/PostgresConnector.py
Frontend/src/pages/ExploreSystems.js

Problem: 
- multiple calls to backend when could be one
- will be a problem when working with more data
Files Changed:
- ExploreSystems.js
- PostgresConnector.py
What changed: Now every time fetchfilteredsystems is called the statistics are automatically calculated. what was previously returned by fetchFilteredSystems is now returned as the first element of an array of results, the rest of which are statistics. All references to the filtered results and statistics are updated to suit the new structure.

Combining getStatistics and getFilteredSystems

---

.github/workflows/linting.yml
.pylintrc
Backend/server.py

**Issue:**
Previously, our repository was lacking code linting to ensure consistent formatting
**What changed:** 
Added a linting yml file and linting rules under .github/workflows and the root directory respectively
**How to experience the change:** 
Make a branch and corresponding PR, then push anything to the branch and check the "checks" tab of the PR to see the github action running.

Implemented basic python linting

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/development-task-template.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md

Added templates to issues and PR

Update issue and PR templates

---

Backend/PostgresConnector.py
Frontend/src/pages/ExploreSystems.js

Fixes #93 
- Error Message Updated
- Indeterminacy Locus Dimension Filter Works
- If a server function fails now it will fail gracefully and you can just refresh the tab
**How it was Changed**
- Added Try/Except statements to allow PostgressConnector to fail gracefully
- Added a Reconnect function to PostgressConnector to re establish the server connection in case of a fail. Calles in getStatistics and getFilteredSystems
- Conditioned Indeterminacy Locus Dimension to work on current data until data is complete
- Updated Error message in ExploreSystems to no longer say Docker
- Indeterminacy Locus Dimension Filter causes the system to break and will not fetch results until the server is restarted
- Whenever the server breaks it must be …

fixing_filters

---

Frontend/src/App.css
Frontend/src/components/FunctionDetail/AdjacencyMatrix.js
Frontend/src/components/FunctionDetail/ModelsTable.js
Frontend/src/components/FunctionDetail/RationalPointsTable.js
Frontend/src/pages/ExploreSystems.js
Frontend/src/pages/SystemDetails.js
docs/style.css

- field label link is now added to field label column of Explore Systems table
- all minor fixes to models table are now finished including the creation of accurate polynomials, display_model field removed, and the correct information in its value in the data dictionary being displayed
- an adjacency matrix is now displayed in the RationalPointsTable upon button press
- stylize like a dialogue box the way that it is meant to be with bootstrap or get ahold of bootstrap style sheets and use selectively. 
[
](url)

Adjacency Matrix Display and other bug fixes. 

---

Backend/postgres_connector.py
Backend/server.py
Frontend/src/App.js
Frontend/src/api/routes.js
Frontend/src/components/Topbar.js
Frontend/src/context/FilterContext.js
Frontend/src/pages/ExploreSystems.js
Frontend/src/pages/Families.js

A new Family filter and a separate page for families is added

Families page- Implemented

---

Backend/config.py
Backend/postgres_connector.py

Fixes #issue_number
*Here, describe the issue that you are fixing with this code, and why your code fixes it.*
*Here, get into detail about what files you modified, and talk about the most important lines in regards to fixing the issue.*
**Screenshots that show the changes (if applicable):**

#148 fix pylint errors in subfields for rational preperiodic filter

---

Backend/config.py
Backend/postgres_connector.py

Fixes #148
In this update:
Backend/config.py: Adjustments were made to the configuration loading script, including fixing pylint issues such as long lines, missing docstrings, trailing whitespaces, and general exception handling. Specifically:
Replaced .format() with f-strings for improved readability.
Replaced a broad Exception with a more specific KeyError.
Renamed the internal variable config to config_data to avoid conflict with the outer scope.
Added a docstring to describe the purpose of the module.
Backend/postgres_connector.py: Removed trailing whitespace from an empty line (line 23).
- Adhere to Python's style guidelines, by resolving pylint warnings.
- Improve code readability and maintainability by switching to f-strings, using more …

#148 fix pylint errors

---

Backend/config.py
Backend/postgres_connector.py

Removed all instances of sigma3 to remove excess bloat in the database.

updated labels for web

---

Backend/config.py
Backend/postgres_connector.py
Frontend/src/pages/SystemDetails.js

Fixes #144
The SystemDetails.js page was modified to include a new section displaying the Automorphism Group. This component was integrated into SystemDetails.js to fetch and display details about the automorphismgroup, for things like cardinality and structure.
The System Details page has a new table added to it titled "Automorphism Group"
Previously the automorphism group section was missing from the details page. This information is important for users who want to understand the automorphisms associated with a given system.
*Here, describe the issue that you are fixing …

Added AutomorphismGroupTable to systemDetails

---

Frontend/src/components/FunctionDetail/FunctionAttributes.js
Frontend/src/pages/SystemDetails.js

Fixes #issue_number
173
A Function Attributes page was added.
The Functions Details page was changed by adding an additional table to it titled "Function Attributes". This table includes boolean values for is_poly, is_pcf, is_newton, is_lattes, and is_chebyshev, as well as displaying the newton model polynomial when relevant.
It was changed to have crucial information readily available to the user for a better experience.
*Here, describe the issue that you are fixing with this code, and why your code fixes it.*
It fixes the issue of not having relevant data readily …

Added function attributes table for issue #173

---

Frontend/src/components/FunctionDetail/ModelsTable.js
babel.config.js
jest.config.js
package-lock.json
package.json
tests/ModelsTable.test.js

Fixes #194 
- Updated ModelsTable.js to display Monic Centered models while ensuring display_model is excluded.
- Added Jest test (ModelsTable.test.js) to check everything works as expected in ModelsTable.js
- We need to show Monic Centered models properly and display_model should not be shown.
- Added tests to catch future errors early.
- Updated ModelsTable.js to fix filtering=> also display 'monic_centered'
- Added Jest tests to check functions (renderExponent, processInput,..) and ModelsTable.js run without without errors.
**Note:**
I ran into some challenges while setting up the tests, as I wasn't entirely familiar with writing test cases. There were a lot of errors, mostly related to missing modules or files, but …

Added Monic Centered Model to ModelsTable.js & Jest Tests

---

Frontend/src/components/FunctionDetail/AutomorphismGroupTable.js
Frontend/src/components/FunctionDetail/CriticalPointPortraitTable.js
Frontend/src/components/FunctionDetail/CriticalPointsTable.js
Frontend/src/components/FunctionDetail/FunctionAttributes.js
Frontend/src/components/FunctionDetail/InfoTable.js
Frontend/src/components/FunctionDetail/ModelsTable.js
Frontend/src/components/FunctionDetail/RationalPointsTable.js

Fixes and finishes #193 
I emailed Dr. Hutz, our client, on the official math definitions, and he has gotten back to me with them. So I took the time to go in and make the updates he wanted, replacing the previous placeholder text for the helpbox tooltips and subtitles. 7 files were changed as 7 tables were updated. Took me some time to do, and I might not get any grade for this, but I just wanted to get this project closer to the finish line.
**Screenshots that show the changes (if applicable):**

Updated math definitions

---

Backend/postgres_connector.py
Backend/server.py
Frontend/src/api/routes.js
Frontend/src/components/FunctionDetail/RationalPointsTable.js

Fixes #179
- Updated the `RationalPointsTable.js` component to include a scrollbar for better handling of large datasets.  
- Introduced a `ScrollableTableContainer` using Material UI's `styled` API to limit the table height and enable vertical scrolling.  
- Added the `stickyHeader` property to the `Table` component to keep the headers visible while scrolling.  
- The table was overflowing when displaying large amounts of data, making it difficult to read and navigate.  
- Adding a scrollbar ensures better usability and readability, allowing users to scroll through large datasets smoothly.  
- Keeping the headers visible with `stickyHeader` improves the user experience by maintaining context while scrolling.  
- **Modified `RationalPointsTable.js`**  
- Wrapped the `TableContainer` in a …

added scrollbar

---

Frontend/src/components/FunctionDetail/RationalPointsTable.js

Fixes #209
Updated the RationalPointsTable component to correctly display rational periodic data. Added Field Label, Cardinality, As Directed Graph, Adjacency Matrix, Cycle Lengths, Component Sizes, Rational Preperiodic Points, and Longest Tail to the table where it now matches the table structure of the other function details tables.
The existing code displayed the table in a format that did not match the other tables on the Function Details page. This change helps maintain the structure and feel of the application. Furthermore, additional and relevant data was added to provide more useful information to the user.
Only RationalPointsTable.js was modified to change the structure and data displayed.

Fixed issue #209: Reformat rational points table

---

Frontend/src/components/FunctionDetail/FunctionAttributes.js
Frontend/src/components/FunctionDetail/ModelsTable.js

- Updated the `FunctionAttributes.js` component to replace `is_chebyshev` with `chebyshev_model`.
- Implemented logic to display the corresponding **Chebyshev polynomial** if the function is classified as Chebyshev.
- If `degree < 10`, the polynomial is retrieved from a **predefined static list**.
- If `degree ≥ 10`, the polynomial is **computed dynamically** using the recurrence relation.
- If the function is **not Chebyshev**, it now displays `"Not Chebyshev"` instead of `true/false`.
- Previously, the `is_chebyshev` field was a boolean (`true/false`), which did not provide enough information.
- The goal was to **display the actual Chebyshev polynomial model** rather than just indicating whether the function is Chebyshev.
- This ensures a more **informative UI** for users analyzing …

chebyshev model computed statically and dynamically

---

Backend/postgres_connector.py
Frontend/public/sage.py
Frontend/src/pages/Definitions.js
Frontend/src/pages/ExploreSystems.js

Fixes #217 
Major changes were made on exporting data from the website.
1. You can now download all the data from the website or just the search results from the website.
2. You can download a static Sage script so users can read and process the CSV data.
3. The CSV file contains all data associated with each mathematical system, including the model label (which had to be built on the fly).
The download dropdown UI was designed to be clean and easy to use.
In addition, the tooltips were modified to match the formatting with the rest of the website. Next, I changed the backend slightly so data can be accessed via its name rather than by its index (to make it more rigorous). Finally, the backend was modified slightly to make the database reconnection after timeout …

Added functionality to export search results with CSV and Sage Compatibility; minor tooltip and backend changes

---

Backend/postgres_connector.py
Frontend/src/components/FunctionDetail/FunctionAttributes.js
Frontend/src/components/FunctionDetail/InfoTable.js
Frontend/src/components/FunctionDetail/ModelsTable.js
Frontend/src/components/FunctionDetail/RationalPointsTable.js
Frontend/src/components/FunctionDetail/RationalTwistsTable.js
Frontend/src/pages/ExploreSystems.js
Installation_Guide.md
README.md
requirements.txt

Fixes nearly all of #230
Many changes were made in the System Details pages.
- The "Download All Data" option was removed from the search page.
- The Chebyshev models (up to degree n=10) have been fixed to be formatted correctly with correct information.
- The Chebyshev column no longer shows if the system is not Chebyshev.
- The domain field has been changed to show accurate data. This required backend changes and a new connection to the backend to pull domain data.
- The field of definition has been changed to show accurate data. This required modifying how the backend accessed the database since there were conflicting columns that caused incorrect data to show.
- The Rational Twists table now has one column for the twists labels
- Newton polynomials are now …

Made many changes to system details pages

---

Frontend/src/components/FunctionDetail/FunctionAttributes.js
Frontend/src/components/FunctionDetail/InfoTable.js
Frontend/src/components/FunctionDetail/ModelsTable.js
Frontend/src/components/FunctionDetail/RationalPointsTable.js
Frontend/src/pages/ExploreSystems.js

Fixes the remainder of #230 
1. All models on the system details page were updated to show up accurately and homogenized, per user request. This required manual generation of the homogenized function. Now the models will show up correctly for any degree and for any coefficient.
2. The Chebyshev polynomials were updated again to be homogenized per client's request, and to be accurate and properly formatted.
3. The CSV file now contains separate columns for each part of each model data.
4. The Newton polynomials were updated to be more rigorous and handle more cases, including negative coefficients.
5. Minor changes to rational points display
These changes were made to satisfy the client's request, finish Issue 230, and have a more accurate …

Made various improvements and refinements to system details pages
