setup.sh

**Issue:** 
Currently, all project setup must be done manually when the project is first cloned from Github. This involves installing all dependencies, starting the python backend and then starting the react frontend. The goal of this issue is to compress these steps into one executable file that can be ran from the command line on any system utilizing Linux, Windows, or MacOS. 
**Changes:** 
A setup file setup.sh has been pushed to the root directory, and was pushed with executable permissions such that the file will be executable when pulled. The file correctly detects and echoes the user's operating system, installs all dependencies, and launches both the backend and frontend. To run the file, on Windows navigate to the root directory of the project and in a command prompt or …

Added project setup file, compatible with MacOS, Linux, and Windows

---

Backend/PostgresConnector.py
Frontend/src/pages/ExploreSystems.js

**Issue:** 
Previously, the 2 filters available  (Degree and Label) under the Field of Definition dropdown tab of the filters section were just placeholder textboxes that did not store any input or pass any inputs into a query to return filtered systems. 
**Code changes:** 
- Updated ExploreSystems.js in the frontend to collect an input from the text boxes
- Changed the Field of Definition Degree textbox in ExploreSystems.js to only accept integers, strings would cause errors/return nothing
- Added fields for Field of Definition Degree and Label to the collected and returned filters json objects in ExploreSystems.js
- Updated buildWhereText method in the backend file PostgresConnector.py to handle string case for Field of Definition Label (format for this parameter is "x.x.x.x" where x is …

Implementing Field of Definition Filters

---

Backend/PostgresConnector.py
Frontend/src/pages/ExploreSystems.js

Issue: 
originally there was no option for input under automorphism group filter on the UI, and the filter was not implemented to be used.
Changes:
there is now a number based input box called cardinality in the automorphism group caret tree, and this can filter the data on when the input is changed only with the up and down buttons. if the input is edited manually and set to empty, the connector will breakdown, this must be looked into further.
*NOTE do not manually change the value, use the up and down arrow buttons to set the input, manually setting the input to empty will break the connector.
filter set to 0
filter set to 1
filter set to 2

Implemented Automorphism Group Cardinality Filter

---

Backend/PostgresConnector.py
Frontend/src/pages/ExploreSystems.js

**Issue:**
1.) Due to filters constantly updating not just on input changes, there was a proneness to missing changes to the filter data structure, glitches that  negated user input, and a possibility for speed issues as we scale up our data.
2.)  the buildWhereText method of the connector was not scalable, and relied on bad coding practices to create conditions for specific filters.
3.) javascript error caused automorphism cardinality filter to interpret 0 as an empty input.
4.) Previously, the Indeterminacy Locus dropdown tab of the filters section was not functional and had no input boxes to add filters, specifically it was missing a dimension filter.
**Code Changes:**
1.)  Button, stylized to fit ui, functions to be the only process that calls the send filters method. Only the button …

get filters button implemented, buildWhereText scaled

---

Frontend/src/pages/ExploreSystems.js

**Issue:**
Previously, the Postcritically Finite tab of the filters section was not functional and had no inputs to add filters, specifically it was missing a Boolean filter for is postcritically finite or is not post critically finite.
Desired functionality has been decided to be adding 3 radio buttons to show PCF, show not PCF, and show all (default). 
**Code changes:**
Updated ExploreSystems.js in the frontend to collect an input from one of three radio buttons, labeled "Is postcritically finite", "not postcritically finite", and "show all". 
Added fields in json objects for getting filtered systems and getting result statistics, and to hold the current value for is_pcf along with the other filter values. 
**Steps to replicate changes:**
Clone issue branch
Run setup file or start …

Implemented Postcritically Finite Filters 

---

Frontend/src/components/newDataTable.js
Frontend/src/context/FilterContext.js
Frontend/src/index.js
Frontend/src/pages/ExploreSystems.js
Frontend/src/pages/SystemDetails.js

Fixes #109 
Added a new context file to store current filter state globally between all pages, which allows filters to be saved and restored when navigating around the website. Pagination is now reset on filter change. To avoid any inconvenience with forgetting to uncheck filters, I added a clear filters button to reset all filters. Additionally, all checkboxes, radio buttons, and text boxes are repopulated upon visiting the explore systems page to indicate the currently selected filters. 
Components modified: 
Added context file
Modified ExploreSystems.js
Modified SystemDetails.js
Wrapped index.js app component in a wrapper to allow for globalization of filters data
To allow for preservation of filters while navigating, keeps track of current …

109 back button for details page save state of the filters

---

Frontend/src/App.css
Frontend/src/components/ActiveFiltersBanner.js
Frontend/src/pages/ExploreSystems.js

Fixes #127 
A banner was added to display active filters as chips rather than finding them manually in the dropdown menus
User convenience and UI improvement
Added an active filters banner reusable component to store the chip logic and display functionality, added css for styling, and added the component into exploresystems.js above the paginated data table
**Screenshots that show the changes (if applicable):**

127 display applied filters at the top

---

Frontend/src/App.css
Frontend/src/components/FunctionDetail/Copy.js
Frontend/src/components/FunctionDetail/ModelsTable.js
Frontend/src/components/FunctionDetail/RationalPointsTable.js
Frontend/src/components/newDataTable.js

- exponents are now displayed as SuperScript in the newDataTable component on the ExplorSystems page, as well as in the ModelsTable in the SystemDetails page. 
- a copy Sage command button is now present to get the Adjacency Matrix and Graph data as a manipulable sage math object.

SuperScripting now rendered, and copy Sage Math Buttons working

---

Backend/config.py
Backend/postgres_connector.py
Frontend/package-lock.json
Frontend/src/pages/ExploreSystems.js

Fixes #149
**What was changed**
This pull request adds new subfields to the Rational Preperiodic Points filter in the ExploreSystems.js file. The following subfields have been added to the UI:
Cardinality
Number of Connected Components
Longest Tail
These additions enhance the filtering capabilities for rational preperiodic points, allowing users to input more specific criteria for their searches.
**Why was it changed**
These changes were implemented to provide users with more granular control over their searches related to rational preperiodic points. By adding these subfields, we enable users to filter dynamical systems based on specific characteristics of their rational preperiodic point structure, which is crucial for various research and analysis tasks in dynamical systems.
**How was …

added requested subfields for rational preperiodic filter

---

Backend/config.py
Backend/postgres_connector.py

…s to make sure the query formats properly
Fixes #141
The `build_where_text()` class was changed. Specifically in the case where the `base_field_label` is used, the input string to `conditons.append()` was changed. 
When the user would enter anything into the `Label` subfield of the `Field of Definition` filter, the application would respond with "no data meets that criteria", even if there was data that should have matched. This made the filter entirely inoperable and the UI less friendly, as there was no indication of what was going wrong on the user side.
In the old code, the entire input was surrounded by two single quotes making the entire text a string, which included a string variable. In addition, the string …

Issue#141/fixing field filter

---

Backend/postgres_connector.py
Frontend/src/pages/ExploreSystems.js

Fixes #143 
Backend logic was added to the Rational Preperiodic Point filters so that the filters are functional.
Last sprint, the subfields for the Rational Preperiodic Point filter were added so that the user would be able to filter by subfields. However, the functionality of the filter was not implemented. So when the user would enter a value, it would appear everything worked however no data was actually filtered out. Therefore we had to implement the filtering on the backend in order to make those subfields functional.
First I had to handle the passing between the front end and the back end so that the filters would actually pass information to the backend. This involved changing the `ExploreSystems.js` file to …

143 rational preperiodic filter not implemented

---

Backend/postgres_connector.py
Frontend/src/context/FilterContext.js
Frontend/src/pages/ExploreSystems.js

Fixes #142
The cardinality sub-filter under rational periodic points has been implemented.
Frontend: modified the filter handling for cp_cardinality so that the correct filter is passed from the UI.
Backend: Updated the database query logic to handle cp_cardinality correctly
This issue was changed so the users can more effectively filter the data they are searching for.
*Here, describe the issue that you are fixing with this code, and why your code fixes it.*
The cardinality filter under Rational Periodic Points was not functioning at all. It was returning all results …

Fix cardinality sub filter for rational periodic point filter #142

---

Frontend/src/components/FunctionDetail/CriticalPointPortraitTable.js
Frontend/src/components/FunctionDetail/CriticalPointsTable.js
Frontend/src/components/FunctionDetail/InfoTable.js

Fixes #159
Fields that display "tmp" were removed.
This changed the function details page by removing the fields Standard Model, Field of Definition, Min Field of Definition, Field of Modull, Cycle Sizes, Critical Points Cardinality, and Post Critical Set.
They were changed because they held the value "tmp"
*Here, describe the issue that you are fixing with this code, and why your code fixes it.*
This removes unnecessary data and provides only relevant fields with meaningful data to be more neatly displayed for the user.
This was changed by deleting …

Remove tmp fields from function details page

---

Backend/postgres_connector.py
Frontend/src/pages/ExploreSystems.js

Fixes #134 
The download button functionality was tweaked so that when the user pressed download an error message wouldn't pop up.
Currently, when the user pressed download for a particular dataset, they encountered errors. This really impacted the experience of the user and made the application seem broken. To fix this, we needed the download button to actually prompt the downloading of a csv file rather than show an error message.
For this change, we found that the `get_selected_systems()` function was bugged in the `postgres_connector.py` file. The query referred to a non-existent `label` column in the database that was causing errors in the query, and in turn, not returning the DB entries that needed to be imported. …

134 download button does not work

---

Backend/postgres_connector.py
Frontend/src/pages/ExploreSystems.js

Fixes #146
What was changed?
The get_statistics() method in the PostgresConnector class was modified to include new statistics about the positive_in_degree column from the graphs_dim_1_nf table.
Why was it changed?
This change was implemented to provide more comprehensive statistics about the graphs in the database. Specifically, it adds information about the average and maximum positive in-degree of the graphs, which can be useful for analyzing the structure and complexity of the graphs in the system.
How was it changed?
The following changes were made to the postgres_connector.py file:
A new SQL query was added to the get_statistics() method to calculate the average and maximum positive_in_degree:
pythonCopysql = (
'SELECT '
'AVG(positive_in_degree) AS avg_positive_in_degree, ' …

statistics page

---

Backend/postgres_connector.py
Frontend/src/pages/ExploreSystems.js

Fixes #165 
The periodic cardinality filter was edited so that the results were filtered on the correct results. In addition, 2 additional filters were added (number of critical points and post critical cardinality).
Originally, the periodic cardinality filter did not filter the intended results. This would result in incorrect values from being reported. This bug might've caused frustration, but it also presented a new possibility for filtering that could provide useful. Sorting via the number of critical points could have a use case so the Postcritically Finite section (now named Critical Points), was edited so that it could accommodate filtering via number of Critical Points. In addition, it also would provide increased functionality if the …

Fixing Filter and adding recommended changes

---

Frontend/src/components/FunctionDetail/CriticalPointPortraitTable.js

Fixes #184 
The table was updated to display the cardinality, size of post critical set, cycle lengths, and component sizes in the correct format. Additionally, the table provides links to show the directed graph and adjacency matrices for the given edges. The structure field was removed from the table. The table will not show up if it is non-PCF. 
This directly solves issue #184, to enhance the critical point portrait table with additional data.
1. The `CriticalPointPotraitTable.js` file was updated. The `TableRows` within the `TableComponent` were updated to correctly show the data from the data variable using the `formatData` function. The `formatData` function was slightly modified so it now returns `N/A` if there …

(Hopefully) Fixed Issue 184 - Enhanced critical point portrait table

---

Backend/package-lock.json
Backend/package.json
Backend/postgres_connector.py
Frontend/src/components/FunctionDetail/AutomorphismGroupTable.js
Frontend/src/components/FunctionDetail/InfoTable.js
Frontend/src/components/FunctionDetail/ModelsTable.js
Frontend/src/pages/ExploreSystems.js

Fixes #187 
**What's Changed?**
- Clickable Base Field Label: Turned base_field_label into a clickable link instead of plain text.
- Updated the Standard Model field in InfoTable.js to display the correct polynomial equation based on display_model. (I still struggle with this part. Now, it just displays the associated raw data of the standard model rather than an equation. The photo below as an example)
- Ensured that the Automorphism Group Cardinality field correctly displays its value in AutomorphismGroupTable.
**Why These Changes?**
Before, it was just text, so users couldn't click on it to access more information. This makes it much more useful.
- Previously, the Standard Model field just showed the standard model type instead of displaying the polynomial equation of the standard …

Fixed Main Function Details Page: Correct Data and Fields

---

Frontend/src/components/FunctionDetail/AutomorphismGroupTable.js
Frontend/src/components/FunctionDetail/CriticalPointPortraitTable.js
Frontend/src/components/FunctionDetail/CriticalPointsTable.js
Frontend/src/components/FunctionDetail/FunctionAttributes.js
Frontend/src/components/FunctionDetail/HelpBox.js
Frontend/src/components/FunctionDetail/InfoTable.js
Frontend/src/components/FunctionDetail/ModelsTable.js
Frontend/src/components/FunctionDetail/MultiplierInvariantsTable.js
Frontend/src/components/FunctionDetail/RationalPointsTable.js

Fixes #193 
To make the website easier to use for the general public, I created a HelpBox component that can be used to show a tooltip (popup) of a definition or explanation. You can hover/click on the help icon, and a popup with the definition pops up. I designed it in a way that it will look and work well on both desktop and mobile devices. The HelpBox component can be modified, so you don't have to go to every file that uses the HelpBox to update it.
In addition, I added subtitles to the tables to help explain the purpose of the table better. I also manually added the help buttons and subtitles to 8 different tables.
Note that placeholder text is used for the tooltips and table subtitles. I will get in touch with our client, Dr. Hutz, soon to get real definitions …

Fixed Issue 193: Added Mathematical Term Definitions Across All Pages with Custom Component

---

Frontend/src/components/FunctionDetail/FunctionAttributes.js
Frontend/src/components/FunctionDetail/InfoTable.js
Frontend/src/components/FunctionDetail/ModelsTable.js
Frontend/src/pages/SystemDetails.js

Fixes #200 
- The Conjugation from Standard column was removed.
- The Automorphism Group table was removed from the System Details page.
- The Family Name field in function details was changed to display the actual family name.
- The Conjugation column was removed because the data is no longer available. This creates a neater display for the user.
- The Automorphism Group table was removed because it no longer provides unique data. Doing this creates a neater display for the user.
- The Family name in function details now shows the actual family name instead of the data id reflecting it. This provides additional clarity for the user on family data.
InfoTable.js, SystemDetails.js, and ModelsTable.js were modified. …

Refactored InfoTable to display family names instead of IDs (Fixes #200)

---

Backend/postgres_connector.py
Backend/server.py
Frontend/src/api/routes.js
Frontend/src/components/FunctionDetail/CriticalPointPortraitTable.js
Frontend/src/components/FunctionDetail/CriticalPointsTable.js
Frontend/src/components/FunctionDetail/ModelsTable.js
Frontend/src/components/FunctionDetail/RationalPointsTable.js
Frontend/src/components/FunctionDetail/RationalTwistsTable.js

Fixes #219 
The Critical Points Table was updated to show data from the graph data table. This required multiple changes in the backend.
I then updated the Rational Twists Display so the model labels are now shown for each Rational Twists system. This required retrieving additional data from the database, constructing the model label for each system, and then updating the UI after the page has been loaded.
Finally, I had the polynomials in the models table no longer show 1 as an exponent. I also added links to the LMFDB for the remaining instances of "Field Label" and "Field of Definition" in the page.
This directly fixes Issue 219 to make these UI updates to make the website more accurate and functional.
Updating the …

Made Minor Fixes for Function Details Display II

---

Backend/postgres_connector.py
tests/test_postgres_connector.py

Fixes #117 
- Updated tests to match real SQL queries and return formats.
- Added tests for edge cases (no result, empty list).
- The original tests didn’t match the updated code and database structure.
- Old tests were failing because of incorrect mocking or outdated expectations.
- I wanted to add more test cases.
- I wanted to make sure core methods like get_all_systems, get_system, and get_selected_systems have working tests.
- Updated unit tests for the PostgresConnector class to match the current database structure and logic.
- Replaced outdated SQL assumptions with the correct table functions_dim_1_NF.
- Mocked database connections and queries using MagicMock and patch.
- Fixed cursor mocking with proper context …

Fixes #117: Write more test cases for the Backend

---

Frontend/src/components/FunctionDetail/FunctionAttributes.js
Frontend/src/pages/ExploreSystems.js

What was changed?
Updated the FunctionAttributes component to ensure the <Table> renders with a consistent number of columns between the header and data rows.
Adjusted font size for the labels "domain", "degree", and "field" in the paginatedDataTable section (line 835 of ExploreSystems.js) to prevent layout wrapping of the associated helpbox components.
Why was it changed?
The table previously rendered an extra, unlabeled column due to a mismatch in the number of <TableCell> elements between the header and body rows, caused by conditional rendering of the "Associated Polynomial" field. This led to layout and alignment issues.
The helpbox tooltips for "domain", "degree", and "field" were wrapping to the next line because the font size of the label text caused overflow. This reduced …

changes to some design elements making it look better
